<div style="text-align: center; padding: 20px; font-family: Vazir;">
<h1 align="center" style="font-size: 28px; color:rgb(64, 244, 202); width: 100%;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>تمرین ۲<br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1>
<h2 style="color:rgb(90, 255, 184); font-size: 20px;">Logistic Regression and Naive Bayes</h2>
<p align="center" style="color: #666; font-size: 16px;">فرهاد نصری - علیرضا زمانی</p>
<p align="center" style="color: #666; font-size: 16px; margin-bottom: 30px;">farhadnasri999@gmail.com - shigzv@gmail.com</p>

<div dir="rtl" style="border: 2px dashed rgb(90, 255, 184); border-radius: 8px; padding: 20px; margin: 20px auto; max-width: 500px; text-align: right;">
<p style="color: rgb(64, 244, 202); font-size: 18px; margin-bottom: 15px;">📝 مشخصات دانشجو:</p>
<p style="color: #666; margin: 5px;">نام و نام خانوادگی: سروش اصفهانیان</p>
<p style="color: #666; margin: 5px;">شماره دانشجویی: 810101376</p>
<p style="color: #666; margin: 5px;">تاریخ ارسال: 1404/8/24</p>
</div>
</div>

<div dir="rtl" style="text-align: justify; padding: 25px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
<div style="padding-right:100px">
📋 <b>ساختار تمرین:</b>
<li><b>سوال اول - <span dir="ltr">Logistic Regression and Naive Bayes (from scratch)</span> (60)</b></li>
<ul>
<li>بخش اول: پیش پردازش داده‌های متنی و استفاده از Bag of Words</li>
<li>بخش دوم: جداسازی داده‌های آموزش و آزمایش</li>
<li>بخش سوم: پیاده‌سازی معیار‌های ارزیابی</li>
<li>بخش چهارم: پیاده‌سازی Logistic Regression</li>
<li>بخش پنجم: پیاده‌سازی Naive Bayes</li>
<li>بخش ششم: تحلیل نتایج</li>
</ul>
<li><b>سوال دوم - <span dir="ltr">Logistic Regression and Naive Bayes (e.g. 
sklearn)</span> (40)</b></li>
<ul>
<li>بخش اول: استخراج ویژگی‌های ساختاری</li>
<li>بخش دوم: استخراج ویژگی‌های آماری و محتوایی</li>
<li>بخش سوم: استخراج ویژگی‌های دلخواه</li>
<li>بخش چهارم: ترکیب همه ویژگی‌های استخراج‌شده</li>
</ul>
</div>
</div>
<div dir='rtl' style="line-height: 1.8; font-family: Vazir; font-size: 16px; margin-top: 20px; background-color: #e8eaf6; padding: 15px; border-radius: 8px; color:black">
💡 <b>نکات مهم:</b>
<br>
در سوال دو مجاز به استفاده از کتابخانه‌های آماده برای مدل‌ها و متریک‌ها هستید ولی در سوال یک، همان‌طور که در متن سوال هم ذکر شده، باید از پایه پیاده‌سازی کنید.
</div>
</div>

# <div style="text-align: center; direction: rtl; font-family: Vazir;"><h1 align="center" style="font-size: 24px; padding: 20px;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>سوال اول: پیاده‌سازی Logistic Regression و Naive Bayes <br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1></div>


<p dir="rtl" style="text-align: right; padding:30px; background-color:rgb(12, 12, 12); border-radius: 12px; color: white; font-family: Vazir;">
در این سوال، شما باید این دو مدل پایه‌ای برای طبقه‌بندی متون را از صفر (بدون استفاده از کتابخانه‌های آماده) پیاده‌سازی کنید. هم‌چنین نیاز است، پیش‌پردازش داده‌ها و ارزیابی عملکرد مدل‌ها را نیز انجام دهید.




## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش اول: پیش پردازش داده‌های متنی و استفاده از Bag of Words</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
در گام پیش‌پردازش، هدف ما آماده‌سازی داده‌های متنی برای استفاده در مدل‌های یادگیری ماشین است. از آن‌جا که مدل‌ها با داده‌های عددی کار می‌کنند، باید متن خام را به شکلی عددی تبدیل کنیم تا بتوانند الگوهای موجود در واژه‌ها را بیاموزند. در این بخش، قصد داریم با تبدیل متون به نمایش Bag of Words، هر ایمیل را بر اساس تعداد تکرار واژه‌هایش به یک بردار عددی تبدیل کنیم.
<br>
دیتاست emails_1.csv شامل دو ستون است:
<br>
text (متن ایمیل)
<br>
status (برچسب، مشخص‌کننده‌ی spam یا ham بودن ایمیل)
<br>
شما باید مراحل زیر را انجام دهید:
<br>
۱. ستون status را به مقادیر عددی تبدیل کنید (spam → 1 و ham → 0).
<br>
۲. متن‌ها را پاک‌سازی کنید: تمام کاراکترهای غیر الفبایی (اعداد، علائم و غیره) را حذف و همه‌ی حروف را کوچک (lowercase) کنید.
<br>
۳. با استفاده از روش Bag of Words، فراوانی کلمات را محاسبه کنید و فقط ۱۵ کلمه‌ی پرتکرار را نگه دارید.
<br>
💡 نکته: برای این بخش می‌توانید از CountVectorizer در کتابخانه‌ی sklearn استفاده کنید.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
یک دیتافریم جدید که شامل ۱۵ ویژگی + ستون status است. (تمام ۱۰ ردیف این دیتافریم را نمایش دهید.)
</p>

In [ ]:
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer

df = pd.read_csv("./datasets/q1/emails_1.csv")
df.iloc[0, :]

text      🎉 Congratulations! You have won a FREE ticket ...
status                                                 spam
Name: 0, dtype: object

In [10]:
def clean_text(text):
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = text.lower()
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# clean up
df['status'] = df['status'].map({'spam': 1, 'ham': 0})
df['text'] = df['text'].apply(clean_text)

# BoW
vectorizer = CountVectorizer(max_features=15)
X_bow = vectorizer.fit_transform(df['text']).toarray()
X_bow_df = pd.DataFrame(X_bow, columns=vectorizer.get_feature_names_out())
preprocess_df = pd.concat([X_bow_df, df['status']], axis=1)
print(preprocess_df)

   and  claim  files  for  free  get  morning  our  please  project  review  \
0    0      1      0    0     2    0        0    1       0        0       0   
1    1      0      1    0     0    0        1    0       1        2       0   
2    0      0      0    2     1    1        0    1       0        0       0   
3    1      0      0    0     0    0        0    0       1        0       1   
4    0      1      0    1     1    0        0    0       0        0       0   
5    0      0      0    0     1    1        0    1       0        0       0   
6    0      0      1    1     0    0        1    0       1        1       0   
7    0      1      0    0     1    0        0    0       0        0       0   
8    1      0      0    1     0    1        0    0       0        0       1   
9    0      0      0    1     0    0        0    0       0        0       0   

   the  to  you  your  status  
0    0   1    1     1       1  
1    1   0    0     1       0  
2    0   0    1     0       1  
3 

<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
از این مرحله به بعد، دیگر با فایل emails_1.csv و دیتافریم حاصل از آن کاری نخواهیم داشت. برای سهولت کار، فایل emails_2.csv در اختیار شما قرار گرفته است. این فایل، نتیجه‌ی همان فرایند پیش‌پردازش بر روی ۵۱۷۲ ایمیل واقعی است. به بیان ساده‌تر، در این مجموعه داده، هر ردیف نمایانگر یک ایمیل و هر ستون نشان‌دهنده‌ی فراوانی یکی از ۳۰۰۰ کلمه‌ی پرتکرار در کل داده‌ها است.
در ادامه، مدل‌هایی که پیاده‌سازی می‌کنید باید روی این مجموعه داده، آموزش داده شوند. بنابراین، در این بخش فایل emails_2.csv را بخوانید و محتوای آن را نمایش دهید تا با ساختار داده آشنا شوید.
</p>



<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
پنج ردیف اول دیتافریم مذکور را نمایش دهید.
</p>

In [23]:
df = pd.read_csv('./datasets/q1/emails_2.csv')
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش دوم: جداسازی داده‌های آموزش و آزمایش</div>

<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
داده‌ها را با نسبت ۸۰ درصد برای آموزش و ۲۰ درصد برای آزمایش تقسیم کنید. در انتها تعداد نمونه‌ها را چاپ کنید.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
X_train, X_test, y_train, y_test<br>
تعداد نمونه‌های X_train و X_test 
</p>

In [30]:
import numpy as np

def divide_samples(data_count, train_ratio=0.8):
    data_idxes = list(range(data_count))
    train_count = int(data_count * train_ratio)
    train_idxes = np.random.choice(data_idxes, size=train_count, replace=False)
    test_idxes = [idx for idx in data_idxes if idx not in train_idxes]
    return train_idxes, test_idxes

def extarct_train_test(df, train_idxes, test_idxes):
    train_rows = df.iloc[train_idxes]
    test_rows = df.iloc[test_idxes]
    return train_rows.drop(['Email No.', 'Prediction'], axis=1), train_rows['Prediction'], test_rows.drop(['Email No.', 'Prediction'], axis=1), test_rows['Prediction']
    
data_count = len(df)
train_idxes, test_idxes = divide_samples(data_count, train_ratio=0.8)
X_train, y_train, X_test, y_test = extarct_train_test(df, train_idxes, test_idxes)

print('Train data:', X_train.head(), y_train.head())
print('\nTest data:', X_test.head(), y_test.head())

Train data:       the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
887    26  15    5   18   10  20  174    0    0  66  ...             0   
2482    1   2    2    1    0   0    5    1    0   1  ...             0   
4884    0   0    1    1    1   0    9    0    0   5  ...             0   
254     5   4    1    0    1   2   22    0    0  10  ...             0   
3807    0   0    1    0    1   0    3    0    0   0  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
887          0    1       0    0               0         0         0   9    0  
2482         0    0       0    0               0         0         0   1    0  
4884         0    0       0    0               0         0         0   0    0  
254          0    0       0    0               0         0         0   1    0  
3807         0    0       0    0               0         0         0   0    0  

[5 rows x 3000 columns] 887     0
2482    1
4884    1
254     

In [31]:
print(f'\nOriginal Sample Count: {data_count}')
print(f'Train Sample Count: {len(X_train)}')
print(f'Test Sample Count: {len(X_test)}')


Original Sample Count: 5172
Train Sample Count: 4137
Test Sample Count: 1035


## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش سوم: پیاده‌سازی معیار‌های ارزیابی</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
پیش از آن‌که وارد مرحله‌ی پیاده‌سازی و آموزش مدل‌های طبقه‌بندی شویم، لازم است معیارهایی برای سنجش عملکرد آن‌ها تعریف کنیم. این معیارها به ما کمک می‌کنند تا بفهمیم مدل تا چه اندازه در تشخیص درست نمونه‌های مثبت و منفی موفق عمل کرده است.
<br>
در این بخش، توابع زیر را برای حالت دودویی (binary classification) پیاده‌سازی کنید:
<br>
accuracy(y_true, y_pred) — نسبت پیش‌بینی‌های درست به کل نمونه‌ها
<br>
precision(y_true, y_pred) — درصد پیش‌بینی‌های مثبت که واقعاً مثبت بوده‌اند
<br>
recall(y_true, y_pred) — درصد نمونه‌های مثبت واقعی که مدل آن‌ها را درست شناسایی کرده است
<br>
f1_score(y_true, y_pred) — میانگین هارمونیک بین precision و recall، برای ایجاد توازن میان آن دو
<br>
هر تابع باید مقدار عددی متناظر با معیار مورد نظر را برگرداند.
<br>
 به توابع بالا دو ورودی زیر را بدهید و خروجی بگیرید:    y_true = [0, 1, 1, 0, 1] ---- y_pred = [0, 1, 0, 0, 1]
<br>
💡 نکته: برای این بخش می‌توانید از  کتابخانه‌ی numpy استفاده کنید.
</p>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
مثال:
<br>
y_true = [0, 1, 1, 0, 1]
<br>
y_pred = [0, 1, 0, 0, 1]
<br>
print(accuracy(y_true, y_pred))  # 0.80
<br>
print(precision(y_true, y_pred)) # 1.00
<br>
print(recall(y_true, y_pred))    # 0.66
<br>
print(f1_score(y_true, y_pred))  # 0.80
<br>
</p>

In [41]:
def get_tp_tn_fp_fn(y_true, y_pred):
    true_class1_indexes = [idx for idx in range(len(y_true)) if y_true[idx] == 1]
    true_class0_indexes = [idx for idx in range(len(y_true)) if y_true[idx] == 0]
    pred_class1_indexes = [idx for idx in range(len(y_true)) if y_pred[idx] == 1]
    pred_class0_indexes = [idx for idx in range(len(y_true)) if y_pred[idx] == 0]
    tp = len(set(true_class1_indexes) & set(pred_class1_indexes))
    tn = len(set(true_class0_indexes) & set(pred_class0_indexes))
    fp = len(set(true_class0_indexes) & set(pred_class1_indexes))
    fn = len(set(true_class1_indexes) & set(pred_class0_indexes))
    return tp, tn, fp, fn

def accuracy(y_true, y_pred):
    tp, tn, fp, fn = get_tp_tn_fp_fn(y_true, y_pred)
    return (tp + tn) / (tp + tn + fp + fn)

def precision(y_true, y_pred):
    tp, tn, fp, fn = get_tp_tn_fp_fn(y_true, y_pred)
    return (tp) / (tp + fp)

def recall(y_true, y_pred):
    tp, tn, fp, fn = get_tp_tn_fp_fn(y_true, y_pred)
    return (tp) / (tp + fn)

def f1_score(y_true, y_pred):
    pre = precision(y_true, y_pred)
    rec = recall(y_true, y_pred)
    return (2 * pre * rec) / (pre + rec)

In [42]:
y_true = [0, 1, 1, 0, 1]
y_pred = [0, 1, 0, 0, 1]

print(accuracy(y_true, y_pred))  # 0.80
print(precision(y_true, y_pred)) # 1.00
print(recall(y_true, y_pred))    # 0.66
print(f1_score(y_true, y_pred))  # 0.80

0.8
1.0
0.6666666666666666
0.8


## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش چهارم: پیاده‌سازی Logistic Regression</div>

<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
کلاس Logistic Regression را به طور کامل پیاده سازی کنید.سپس مدل را بر روی داده‌های train آموزش دهید و در انتها دقت مدل را باتوجه به متریک های تعریف شده بر روی داده‌های test گزارش کنید.
<br>
💡استفاده از هایپر پارامتر‌های مناسب مانند نرخ یادگیری و تعداد دوره‌های آموزش بر عهده خودتان است.
<br>
💡میتوانید قبل از آموزش داده ها را نرمال سازی کنید.
<br>
💡مجاز به استفاده از کتابخانه اماده نیستید.
</p>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
معیار‌های پیاده سازی شده را بر روی داده‌های test خروجی بگیرید و نتایج را چاپ کنید
</p>

In [46]:
class Logistic_Regression:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None
        
    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def _normalize(self, X):
        return (X - np.mean(X, axis=0)) / (np.std(X, axis=0) + 1e-8)

In [51]:
def fit(self, X, y, normalize=True):
    X = np.array(X)
    y = np.array(y)
    
    if normalize:
        X = self._normalize(X)
    
    n_samples, n_features = X.shape
    self.weights = np.zeros(n_features)
    self.bias = 0
    
    # SGD
    for i in range(self.n_iters):
        linear_model = np.dot(X, self.weights) + self.bias
        y_pred = self._sigmoid(linear_model)
    
        # gradients
        dw = (1 / n_samples) * np.dot(X.T, (y_pred - y))
        db = (1 / n_samples) * np.sum(y_pred - y)
    
        # update
        self.weights -= self.lr * dw
        self.bias -= self.lr * db
        
        # report
        print(f'Iteration: {i}/{self.n_iters}, Loss: {np.sum(y_pred - y):.3f}')    

Logistic_Regression.fit = fit

In [48]:
def predict_proba(self, X, normalize=True):
    X = np.array(X)
    if normalize:
        X = self._normalize(X)
    linear_model = np.dot(X, self.weights) + self.bias
    return self._sigmoid(linear_model)

def predict(self, X, normalize=True):
    y_pred_proba = self.predict_proba(X, normalize)
    return np.where(y_pred_proba >= 0.5, 1, 0)

Logistic_Regression.predict_proba = predict_proba
Logistic_Regression.predict = predict

In [59]:
lr = 0.01
iter_count = 1500
logistic_regression_model = Logistic_Regression(learning_rate=lr, n_iters=iter_count)

In [60]:
logistic_regression_model.fit(X_train, y_train)

Iteration: 0/1500, Loss: 878.500
Iteration: 1/1500, Loss: 874.586
Iteration: 2/1500, Loss: 868.344
Iteration: 3/1500, Loss: 861.624
Iteration: 4/1500, Loss: 854.871
Iteration: 5/1500, Loss: 848.184
Iteration: 6/1500, Loss: 841.577
Iteration: 7/1500, Loss: 835.047
Iteration: 8/1500, Loss: 828.585
Iteration: 9/1500, Loss: 822.185
Iteration: 10/1500, Loss: 815.841
Iteration: 11/1500, Loss: 809.552
Iteration: 12/1500, Loss: 803.316
Iteration: 13/1500, Loss: 797.133
Iteration: 14/1500, Loss: 791.003
Iteration: 15/1500, Loss: 784.927
Iteration: 16/1500, Loss: 778.905
Iteration: 17/1500, Loss: 772.939
Iteration: 18/1500, Loss: 767.030
Iteration: 19/1500, Loss: 761.177
Iteration: 20/1500, Loss: 755.382
Iteration: 21/1500, Loss: 749.645
Iteration: 22/1500, Loss: 743.967
Iteration: 23/1500, Loss: 738.346
Iteration: 24/1500, Loss: 732.785
Iteration: 25/1500, Loss: 727.282
Iteration: 26/1500, Loss: 721.837
Iteration: 27/1500, Loss: 716.451
Iteration: 28/1500, Loss: 711.123
Iteration: 29/1500, Loss

In [61]:
y_pred = list(logistic_regression_model.predict(X_test))
y_true = list(y_test)

print('Accuracy:', f'{accuracy(y_true, y_pred):.3f}') 
print('Precision:', f'{precision(y_true, y_pred):.3f}')
print('Recall:', f'{recall(y_true, y_pred):.3f}')   
print('F1 Score:', f'{f1_score(y_true, y_pred):.3f}') 

Accuracy: 0.964
Precision: 0.969
Recall: 0.910
F1 Score: 0.938


## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش پنجم: پیاده‌سازی Naive Bayes</div>

<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
کلاس Multinomial Naive Bayes را به طور کامل پیاده سازی کنید. سپس مدل را بر روی داده‌های train آموزش دهید و در انتها دقت مدل را باتوجه به معیار های تعریف شده بر روی داده‌های test گزارش کنید.
<br>
- چرا از مدل‌های دیگر مانند Gaussian Naive Bayes استفاده نکردیم؟ آیا از مدل‌های دیگر Naive Bayes می‌توان استفاده کرد؟
<br>
💡مجاز به استفاده از کتابخانه اماده نیستید.
<br>
💡برای آشنایی با Naive Bayes می‌توانید به Appendix کتاب jurafsky مراجعه کنید.
</p>

<p style="direction: rtl; text-align: right; background:#fffbe6; font-family: Vazir; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111">
✍️ <b>پاسخ تشریحی بخش پنجم:</b><br>
مدل Multinomial Bayes برای مدل کردن داده‌هایی با مقادیر گسسته مانند تعداد هر مولفه در هر نمونه و... به کار می‌رود و احتمالی که محاسبه می‌کند با تعداد وقوع آن ویژگی در نمونه ارتباط دارد و معمولا برای کاربردهایی که در آن داده به صورت Bag of words و یا مقادیر Term Frequency است، استفاده می‌شود و از این رو، بهترین انتخاب برای استفاده بر روی مجموعه واژه‌های ما می‌باشد.
<br>
 مدل Gaussian Naive Bayes اما، برای مدل‌سازی مقادیر پیوسته به کار می‌رود و برای هر ویژگی مانند x، فرض می‌کند توزیع P(x∣C) از یک توزیع گاوسی یا نرمال پیروی می‌کند. از این رو و به دلیل کار با مقادیر پیوسته، کاربردهای معمول این مدل در دادگان با مقادیر پیوسته مانند داده‌های خروجی سنسورها، مجموعۀ دادۀ حاصل از PCA، مقادیر پیوسته embeddngها و... می‌باشد و برای کاربرد کنونی که حاوی مقادیر گسسته از تعداد کلمات در نمونه‌ها است، انتخاب چندان مناسبی نمی‌باشد.
<br>
به عنوان گزینۀ دیگر، می‌توان از مدل Bernoulli Naive Bayes نیز استفاده کرد که به جای در نظر گرفتن تعداد وقوع یک کلمه در نمونه، وجود و یا عدم وجود آن را در نمونه در نظر می‌گیرد و به تعداد وقوع آن کاری ندارد، به عبارت دیگر هر ویژگی در این مدل، مقدار binary است که وجود و یا عدم وجود کلمه در نمونه را نشان می‌دهد و در مواردی که تعداد وقوع کلمه اهمیتی ندارد، قابل استفاده است.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
معیار‌های پیاده سازی شده را بر روی داده‌های test خروجی بگیرید و نتایج را چاپ کنید
</p>

In [63]:
class MN_Naive_Bayes:
    def __init__(self, alpha=1.0):
        self.alpha = alpha
        self.class_log_prior_ = None
        self.feature_log_prob_ = None
        self.classes_ = None
        self.normalize = False
        self.X_mean = None
        self.X_std = None
        
    def _normalize(self, X):
        return (X - self.X_mean) / (self.X_std + 1e-8)

In [64]:
def fit(self, X, y, normalize=False):
        X = np.array(X, dtype=float)
        y = np.array(y)
        self.normalize = normalize

        if normalize:
            self.X_mean = np.mean(X, axis=0)
            self.X_std = np.std(X, axis=0)
            X = self._normalize(X)

        n_samples, n_features = X.shape
        self.classes_, class_counts = np.unique(y, return_counts=True)
        n_classes = len(self.classes_)

        # log(P(class))
        self.class_log_prior_ = np.log(class_counts / n_samples)

        # P(feature|class)
        feature_count = np.zeros((n_classes, n_features))
        for idx, c in enumerate(self.classes_):
            X_c = X[y == c]
            feature_count[idx, :] = X_c.sum(axis=0)

        # Laplace smoothing
        smoothed_fc = feature_count + self.alpha
        smoothed_denom = smoothed_fc.sum(axis=1).reshape(-1, 1)
        self.feature_log_prob_ = np.log(smoothed_fc / smoothed_denom)

MN_Naive_Bayes.fit = fit

In [65]:
def predict_log_proba(self, X):
    X = np.array(X, dtype=float)
    if self.normalize:
        X = self._normalize(X)
    
    # log P(C) + Σ X_i * log P(word_i|C)
    return self.class_log_prior_ + X.dot(self.feature_log_prob_.T)

def predict(self, X):
    log_probs = self.predict_log_proba(X)
    class_indices = np.argmax(log_probs, axis=1)
    return self.classes_[class_indices]

MN_Naive_Bayes.predict_log_proba = predict_log_proba
MN_Naive_Bayes.predict = predict

In [66]:
bayes_model = MN_Naive_Bayes(alpha=1.0)

In [67]:
bayes_model.fit(X_train, y_train)

In [68]:
y_pred = list(bayes_model.predict(X_test))
y_test = list(y_test)

print('Accuracy:', f'{accuracy(y_true, y_pred):.3f}') 
print('Precision:', f'{precision(y_true, y_pred):.3f}')
print('Recall:', f'{recall(y_true, y_pred):.3f}')   
print('F1 Score:', f'{f1_score(y_true, y_pred):.3f}') 

Accuracy: 0.955
Precision: 0.907
Recall: 0.945
F1 Score: 0.926


## <div style="text-align: center; direction: rtl; font-family: Vazir;"> بخش ششم: تحلیل نتایج</div>

<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
نتایج دو مدل پیاده سازی شده را با یکدیگر مقایسه کنید و تحلیلی بر نتایج داشته باشید.<br>
    
</p>

To compare the models' performance:

| Model                     | Accuracy(%) | Precision(%) | Recall(%) | F1 Score(%) |
|---------------------------|----------|-----------|--------|----------|
| Logistic Regression       | 96.4    | 96.9     | 91.0  | 93.8    |
| Multinomial Naive Bayes   | 95.5    | 90.7     | 94.5  | 92.6    |

<p style="direction: rtl; text-align: right; background:#fffbe6; font-family: Vazir; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111">
✍️ <b>پاسخ تشریحی بخش ششم:</b><br>
همان‌طور که در جدول نیز قابل مشاهده است، هر دو مدل عملکرد بسیار خوبی بر روی تسک تعریف شده داشته اند و مقدار معیارها برای هر دو مدل بالا می‌باشد. از لحاظ مقایسۀ بین دو مدل نیز، هر چند که اختلافشان بسیار ناچیز است و هر دو عملکرد خوبی داشته اند، می‌توان گفت مدل رگرسیون لجستیک با دقت ۹۶.۴٪ عملکرد بهتری نسبت به مدل بیزی چندجمله‌ای با دقت ۹۵.۵٪ نشان می‌دهد. رگرسیون لجستیک در شاخص‌های دقت (Precision) و امتیاز F1 نیز عملکرد بالاتری دارد، که نشان می‌دهد در تشخیص درست نمونه‌های اسپم و جلوگیری از خطاهای مثبت کاذب بهتر عمل می‌کند. در مقابل، مدل بیزی چندجمله‌ای با وجود دقت کمتر، Recall بالاتری (۹۴.۵٪) ارائه داده است، که نشان می‌دهد در شناسایی موارد اسپم واقعی حساس‌تر است، اما ممکن است تعداد بیشتری تشخیص اشتباه داشته باشد. در مجموع می‌توان گفت که رگرسیون لجستیک مدلی پایدارتر و دقیق‌تر از نظر انواع خطا ارائه می‌دهد.
</p>


# <div style="text-align: center; direction: rtl; font-family: Vazir;"><h1 align="center" style="font-size: 24px; padding: 20px;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>سوال دوم: استفاده از Logistic Regression و Naive Bayes <br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1></div>


<p dir="rtl" style="text-align: right; padding:30px; background-color:rgb(12, 12, 12); border-radius: 12px; color: white; font-family: Vazir;">هدف این سوال، بررسی و مقایسه عملکرد مدل‌های Logistic Regression و Naive Bayes در تشخیص لینک‌های فیشینگ از لینک‌های قانونی (معتبر) است.
شما باید با استفاده از مجموعه‌داده‌ی ارائه‌شده (آدرس‌های اینترنتی خام)، یک سری ویژگی‌های عددی از این URLها استخراج نمایید و تأثیر انتخاب ویژگی‌ها و نرمال‌سازی داده‌ها را بر عملکرد مدل‌ها بررسی کنید.<br>نکته: در این سوال مجاز به استفاده از کتاب‌خانه‌های آماده هستید.


## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش اول: ویژگی‌های ساختاری</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
سه ویژگی زیر را از آدرس استخراج کنید:
<br>
- تعداد نقطه‌ها (nb_dots)
<br>
- تعداد اسلش‌ها (nb_slashes)
<br>
- تعداد خط ‌تیره‌ها (nb_hyphens)
<br>
سپس با این سه ویژگی مدل‌ها را روی هشتاد درصد داده‌ها (داده‌های آموزش) آموزش دهید و روی بیست درصد داده‌ها (داده‌های آزمون) مقایسه کنید
<br>
<br>
- آیا لازم است این ویژگی‌ها را نرمال‌سازی کنید؟ چرا؟ اگر پاسخ شما «بله» است، نوع نرمال‌سازی را توضیح دهید و آن را اجرا کنید.
<br>
- به نظر شما از بین نسخه‌های مختلف Naive Bayes (GaussianNB یا MultinomialNB) کدام برای داده‌های شما مناسب‌تر است؟ دلیل خود را بنویسید و با آن مدل آزمایش را انجام دهید.
</p>

<p style="direction: rtl; text-align: right; background:#fffbe6; font-family: Vazir; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111">
✍️ <b>پاسخ تشریحی بخش اول:</b>
<br>
- برای مدل Logistic Regression، بهتر است عملیات نرمال‌سازی انجام شود چرا که این مدل نسبت به مقادیر و مقیاس ویژگی‌ها حساسیت دارد و مقادیر غیر معمول و یا خیلی بزرگ یا کوچک می‌تواندن بر عملکرد مدل و الگوریتم بهینه‌سازی اثرگذار باشد. در خصوص مدل Naive Bayes، نرمال‌سازی واجب نیست، چرا که این مدل فرض می‌کند ویژگی‌ها از یک‍دیگر مستقل هستند و در آخر، احتمال تعلق به یک دسته را نسبت به نرخ وقوع حساب می‌کند و در نتیجه مقدار یک ویژگی به طور مستقیم و نرمال‌سازی و یا عدم نرمال‌سازی تاثیر چندانی بر عملکرد مدل ندارد. از آن جایی که نرمال‌سازی برای مدل رگرسیون می‌تواند مفید باشد و در عملکرد مدل Naive Bayes تاثیر چندانی ندارد، داده را نرمال‌سازی می‌کنیم؛ هر چند که می‌توان در هنگام آموزش مدل Bayes از داده‌های نرمال‌سازی نشده استفاده کرد.
<br><br>
- در میان دو گزینۀ Gaussian و یا Multinomial، همان‌طور که در سوال قبل نیز توضیح داده شد، مدل Multinomial برای آموزش بر روی داده‌های گسسته که تعداد یک ویژگی در نمونه را نشان می‌دهند مناسب است در حالی که مدل Gaussian در مواقعی به کار می‌رود که ویژگی‌ها پیوسته باشند و با فرض پیروی از توزیع نرمال فرآیند یادگیری را انجام می‌دهد. بنابراین، با توجه به نوع ویژگی‌ها در این سوال، مدل Multinomial مدل بهتری است.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- جدولی (دیتافریم) شامل ۳ ویژگی استخراج‌شده + برچسب هدف (status)<br>
- جدول مقایسه‌ای شامل Accuracy, Precision, Recall, F1-score برای هر مدل
</p>

In [2]:
import pandas as pd

df = pd.read_csv('./datasets/q2/urls.csv')
print(df.columns)
print(df.shape)

Index(['url', 'status'], dtype='object')
(11430, 2)


In [22]:
def extract_features_from_url(url):
    return {
        "nb_dots": url.count('.'),
        "nb_slashes": url.count('/'),
        "nb_hyphens": url.count('-')
    }

def extract_features_from_df(df, url_column="url"):
    feature_rows = []
    for url in df[url_column]:
        feature_rows.append(extract_features_from_url(url))

    features_df = pd.DataFrame(feature_rows)
    features_df = pd.concat([features_df, df['status']], axis=1)
    return features_df

features_df = extract_features_from_df(df)
print(features_df.shape)
print(features_df.head())

(11430, 4)
   nb_dots  nb_slashes  nb_hyphens      status
0        3           3           0  legitimate
1        1           5           0    phishing
2        4           5           1    phishing
3        2           2           0  legitimate
4        2           5           2  legitimate


Now, to normalize and split the feature dataset:

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = features_df.drop(['status'], axis=1)
labels_dict = {'legitimate': 0, 'phishing': 1}
y = [labels_dict[lbl] for lbl in list(features_df['status'])]

# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# normalize
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Now, to train the Logistic Regression model:

In [24]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)
y_pred_lr = log_reg.predict(X_test_scaled)

And to train the Multinomial Naive Bayes model:

In [25]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

Now, we compute the comparison metrics:

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def get_metrics(y_true, y_pred):
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred),
        "recall": recall_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred)
    }

metrics_lr = get_metrics(y_test, y_pred_lr)
metrics_nb = get_metrics(y_test, y_pred_nb)

print('Logistic Regression Model:', *[(key, f'{val:.4f}') for (key, val) in metrics_lr.items()], sep='\n')
print('\nMultinomial Naive Bayes model:', *[(key, f'{val:.4f}') for (key, val) in metrics_nb.items()], sep='\n')

Logistic Regression Model:
('accuracy', '0.6763')
('precision', '0.7042')
('recall', '0.6080')
('f1', '0.6526')

Multinomial Naive Bayes model:
('accuracy', '0.5424')
('precision', '0.5286')
('recall', '0.7830')
('f1', '0.6312')


To visualize the comparison:

| Model                     | Accuracy(%) | Precision(%) | Recall(%) | F1 Score(%) |
|---------------------------|----------|-----------|--------|----------|
| Logistic Regression       | 67.63    | 70.42     | 60.80  | 65.26    |
| Multinomial Naive Bayes   | 54.24    | 52.86     | 78.30  | 63.12    |

## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش دوم: ویژگی‌های آماری و محتوایی</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
سه ویژگی زیر را از آدرس استخراج کنید:
<br>
- طول کل آدرس (length_url)
<br>
- نسبت تعداد ارقام (0–9) به کل طول آدرس (ratio_digits_url)
<br>
- طولانی‌ترین کلمه (کاراکترهای الفبایی) در URL که با علائم جداساز (نقطه، علامت‌سوال، اسلش و...) از هم جدا شده‌اند. (longest_words_raw)
<br>
سپس با این سه ویژگی مدل‌ها را روی هشتاد درصد داده‌ها (داده‌های آموزش) آموزش دهید و روی داده‌های آزمون (بیست درصد داده‌ها) مقایسه کنید.
<br>
- به نظر شما استفاده از Naive Bayes برای این ویژگی‌ها منطقی است؟ توضیح دهید. کدام نسخه مناسب‌تر است؟ 
</p>

<p style="direction: rtl; text-align: right; background:#fffbe6; font-family: Vazir; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111">
✍️ <b>پاسخ تشریحی بخش دوم:</b><br>
- با توجه به اینکه ویژگی‌های حاصل در این قسمت از نوع مقادیر پیوسته مانند نسبت گفته شده و یا از نوع مقدار طول می‌باشند، استفاده از مدل رگرسیون می‌تواند مناسب‌تر باشد و این مدل معمولا در کار با مقادیر پیوسته عملکرد مناسبی دارد. همچنین با توجه به ویژگی‌ها، واضح است که ویژگی‌ها از یکدیگر مستقل نیستند؛ برای مثال، طول آدرس که ویژگی اول است، بر ویژگی دوم (و یا حتی سوم) نیز تاثیرگذار است، در حالی که مدل Bayes فرض می‌کند ویژگی‌های داده از یک‌دیگر مستقل هستند و بنابراین استفاده از مدل Bayes بر روی این مجموعه ویژگی‌ها مورد سوال است. همچنین در میان انواع مدل‌های Bayes، به علت پیوسته و از جنس مقدار طول بودن ویژگی‌ها، همان‌طور که پیش‌تر توضیح داده شد، استفاده از مدل Gaussian Bayes در اینجا نسبت به دو مدل Mutlinomial و یا Bernoulli مناسب‌تر است و معمولا از این مدل برای آموزش هنگامی که ویژگی پیوسته است به کار می‌رود.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- جدولی (دیتافریم) شامل ۳ ویژگی استخراج‌شده + برچسب هدف (status)<br>
- جدول مقایسه‌ای شامل Accuracy, Precision, Recall, F1-score برای هر مدل
</p>

In [157]:
import re

def extract_cont_features_from_url(url):
    url_length = len(url)

    # count digits and ratio
    num_digits = sum(c.isdigit() for c in url)
    ratio_digits = num_digits / url_length if url_length > 0 else 0

    # length of longest word
    separators = r'[./?&#_=:\-]'
    words = re.split(separators, url)
    longest_word_len = max((len(w) for w in words if w.isalpha()), default=0)

    return {
        "length_url": url_length,
        "ratio_digit_url": ratio_digits,
        "longest_words_raw": longest_word_len
    }
    
def extract_cont_features_from_df(df, url_column="url"):
    feature_rows = []
    for url in df[url_column]:
        feature_rows.append(extract_cont_features_from_url(url))
    features_df = pd.DataFrame(feature_rows)
    features_df = pd.concat([features_df, df['status']], axis=1)
    return features_df

cont_features_df = extract_cont_features_from_df(df)
print(cont_features_df.shape)
print(cont_features_df.head())

(11430, 4)
   length_url  ratio_digit_url  longest_words_raw      status
0          37         0.000000                 11  legitimate
1          77         0.220779                 19    phishing
2         126         0.150794                 13    phishing
3          18         0.000000                  5  legitimate
4          55         0.000000                 11  legitimate


In [158]:
X = cont_features_df.drop(['status'], axis=1)
y = [labels_dict[lbl] for lbl in list(cont_features_df['status'])]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [159]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)
y_pred_lr = log_reg.predict(X_test_scaled)

In [160]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train_scaled, y_train)
y_pred_nb = gnb.predict(X_test_scaled)

In [161]:
metrics_lr = get_metrics(y_test, y_pred_lr)
metrics_nb = get_metrics(y_test, y_pred_nb)

print('Logistic Regression Model:', *[(key, f'{val:.4f}') for (key, val) in metrics_lr.items()], sep='\n')
print('\nGaussian Naive Bayes model:', *[(key, f'{val:.4f}') for (key, val) in metrics_nb.items()], sep='\n')

Logistic Regression Model:
('accuracy', '0.6483')
('precision', '0.6955')
('recall', '0.5276')
('f1', '0.6000')

Gaussian Naive Bayes model:
('accuracy', '0.6387')
('precision', '0.7569')
('recall', '0.4086')
('f1', '0.5307')


To visualize the comparison:

| Model                     | Accuracy(%) | Precision(%) | Recall(%) | F1 Score(%) |
|---------------------------|----------|-----------|--------|----------|
| Logistic Regression       | 64.83    | 69.55     | 52.76  | 60.00    |
| Gaussian Naive Bayes   | 63.87    | 75.69     | 40.86  | 53.07    |

## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش سوم: ویژگی‌های خلاقانه</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
سه ویژگی به انتخاب خودتان از آدرس‌ها استخراج نمایید و مشابه دو بخش قبلی، مدل‌ها را آموزش دهید.
برای هر ویژگی توضیح دهید چرا ممکن است در تشخیص فیشینگ مؤثر باشد؟
</p>

<p style="direction: rtl; text-align: right; background:#fffbe6; font-family: Vazir; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111">
✍️ <b>پاسخ تشریحی بخش سوم:</b><br>
ویژگی‌های استخراج‌شده از داده به صورت زیر می‌باشند:
<br><br>
1- نسبت کاراکترهای غیرمعمول به طول آدرس (suspicious_char_ratio): این ویژگی نسبت تعداد کاراکترهای غیرمعمول به طول url را نشان می‌دهد و به نوعی متناظر با ویژگی دوم در بخش قبل می‌باشد. از آن جایی که در لینک‌های مربوط به فیشینگ، تعداد کاراکترهای غیرمعمول به طور کلی بیشتر است، این ویژگی می‌تواند در تشخیص فیشینگ بودن یا نبودن یک نمونه داده موثر باشد.
<br><br>
2- نوع TLD استفاده شده در دامنه (tld_risk): به صورت معمول، لینک‌های فیشینگ از تعدادی TLD بیش از سایر TLDهای دارای اعتبار بیشتر استفاده می‌کنند. به عبارت دیگر، می‌توان به نوع TLD استفاده شده در لینک یک ضریب ریسک نسبت داد که مشخص می‌کند چه مقدار استفاده از آن در لینک‌های فیشینگ رایج است. در  لینک‌های فیشینگ، به طور معمول استفاده از TLDهایی مانند .xyz, .top, .info, .club, .pw, .gq, .ml, .cf, .tk رایج است در حالی که TLDهایی مثل .com, .org, .edu و یا TLDهای مربوط به کشورها و... ریسک کمتری از منظر استفاده در لینک‌های فیشینگ دارند. بدین ترتیب، این ضریب ریسک می‌تواند در تشخیص لینک‌های فیشینگ موثر باشد.
<br><br>
3- استفاده از نام برندهای مطرح (brand_count): این ویژگی نشان می‌دهد که آیا در لینک نام برند و یا شرکت مطرحی عنوان شده است یا خیر، چرا که لینک‌های فیشینگ به طور معمول تمایل دارند برندهای شناخته شده را هدف خود قرار دهند و اکثر فیشینگ‌ها مربوط به سواستفاده از آدرس‌های صفحات برندهای مطرح است و از آن‌ جایی که این مورد در مجموعۀ داده نیز قابل مشاهده است، این ویژگی می‌تواند به تشحخیص فیشینگ کمک کند.
<br><br>
برای ویژگی دوم و سوم و برای اینکه مدل بتواند تعمیم‌پذیری خوبی داشته باشد، سعی شده است مجموعه‌ای جامع از انواع TLDها و اسامی خاص و برندها ارائه شود تا مدل بتواند در حد امکان بر روی داده‌هایی که تا به الآن آن‌ها را ندیده‌ است نیز عملکرد قابل قبولی داشته باشد.
<br><br>
برای مدل بیزی، با توجه به وجود هر دو نوع ویژگی گسسته و پیوسته در میان این سه ویژگی، عملکرد هر دو مدل را در کنار مدل رگرسیون آزموده‌ایم. 
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- جدولی (دیتافریم) شامل ۳ ویژگی استخراج‌شده + برچسب هدف (status)<br>
- جدول مقایسه‌ای شامل Accuracy, Precision, Recall, F1-score برای هر مدل
</p>

In [ ]:
import tldextract

HIGH_RISK_TLDS = {
    "xyz", "top", "info", "club", "online", "site", "pw", "work", "click",
    "link", "press", "review", "kim", "win", "men", "bid", "loan",
    "trade", "download", "country", "party", "science", "date",
    "faith", "gdn", "asia",
    "ru", "cn", "tk", "ml", "ga", "cf", "gq", "su", "pl",
    "vn", "ke", "ng",
    "icu", "host", "app", "shop", "vip", "buzz", "rest", "fit",
    "cam", "fun", "stream", "space", "life", "today", "live",
    "zip", "mov",
    "ag", "uy", "vu", "to", "ws", "la",
    "eth", "crypto"
}

MEDIUM_RISK_TLDS = {
    "net", "biz", "me", "tv", "mobi", "name",
    "co", "io", "tech", "pro", "cloud", "solutions", "services",
    "media", "group", "digital", "systems", "center",
    "support", "tools", "world", "global", "uk", "es", "in"
}


COMMON_BRANDS = [
    "apple", "paypal", "google", "amazon", "microsoft", "facebook",
    "instagram", "netflix", "spotify", "adobe", "icloud",
    "bankofamerica", "chase", "wellsfargo", "hsbc", "barclays",
    "citibank", "capitalone", "amex", "boa", "verizon", "att",
    "coinbase", "binance", "kraken", "blockchain", "paypal-secure",
    "irs", "usps", "fedex", "dhl", "ups", "hmrc", "revenue",
    "secure", "update", "login", "verify", "account", "credential",
    "billing", "authenticate", "reset", "unlock", "support",
    "service", "customer", "protection", "alert", "notification",
    "webscr", "auth", "secureupdate", "signin", "verification",
    "portal", "session", "token", "validate"
]

def extract_creative_features_from_url(url):
    extracted = tldextract.extract(url)
    subdomain = extracted.subdomain
    tld = extracted.suffix

    # suspicious chars
    suspicious_chars = re.findall(r'[^A-Za-z0-9]', url)
    suspicious_ratio = len(suspicious_chars) / len(url) if len(url) > 0 else 0

    # tld risk value
    tld_clean = tld.lower()
    if tld_clean in HIGH_RISK_TLDS:
        tld_risk = 2
    elif tld_clean in MEDIUM_RISK_TLDS:
        tld_risk = 1
    else:
        tld_risk = 0
    
    # number of brands impersonated
    url_lower = url.lower()
    brand_hits = sum(1 for brand in COMMON_BRANDS if brand in url_lower)

    return {
        "suspicious_char_ratio": suspicious_ratio,
        "tld_risk": tld_risk,
        "brand_count": brand_hits
    }
    
def extract_creative_features_from_df(df, url_column="url"):
    feature_rows = []

    for url in df[url_column]:
        feature_rows.append(extract_creative_features_from_url(url))
    
    features_df = pd.DataFrame(feature_rows)
    features_df = pd.concat([features_df, df['status']], axis=1)    
    return features_df

creative_features_df = extract_creative_features_from_df(df)
print(creative_features_df.shape)
print(creative_features_df.head(10))

(11430, 4)
   suspicious_char_ratio  tld_risk  brand_count      status
0               0.189189         0            0  legitimate
1               0.090909         0            0    phishing
2               0.150794         0            5    phishing
3               0.277778         0            0  legitimate
4               0.181818         0            0  legitimate
5               0.250000         1            1    phishing
6               0.263158         0            0  legitimate
7               0.098765         0            0    phishing
8               0.142857         0            0  legitimate
9               0.173077         0            0  legitimate


In [152]:
X = creative_features_df.drop(['status'], axis=1)
y = [labels_dict[lbl] for lbl in list(cont_features_df['status'])]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [153]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)
y_pred_lr = log_reg.predict(X_test_scaled)

In [154]:
gnb = MultinomialNB()
gnb.fit(X_train, y_train)
y_pred_nb_mn = gnb.predict(X_test)

In [155]:
gnb = GaussianNB()
gnb.fit(X_train_scaled, y_train)
y_pred_nb_gaussian = gnb.predict(X_test_scaled)

In [156]:
metrics_lr = get_metrics(y_test, y_pred_lr)
metrics_nb_mn = get_metrics(y_test, y_pred_nb_mn)
metrics_nb_gs = get_metrics(y_test, y_pred_nb_gaussian)

print('Logistic Regression Model:', *[(key, f'{val:.4f}') for (key, val) in metrics_lr.items()], sep='\n')
print('\nMultinomial Naive Bayes model:', *[(key, f'{val:.4f}') for (key, val) in metrics_nb_mn.items()], sep='\n')
print('\nGaussian Naive Bayes model:', *[(key, f'{val:.4f}') for (key, val) in metrics_nb_gs.items()], sep='\n')

Logistic Regression Model:
('accuracy', '0.7017')
('precision', '0.7581')
('recall', '0.5923')
('f1', '0.6650')

Multinomial Naive Bayes model:
('accuracy', '0.6549')
('precision', '0.8266')
('recall', '0.3920')
('f1', '0.5318')

Gaussian Naive Bayes model:
('accuracy', '0.6697')
('precision', '0.7828')
('recall', '0.4698')
('f1', '0.5872')


To visualize the comparison:

| Model                     | Accuracy(%) | Precision(%) | Recall(%) | F1 Score(%) |
|---------------------------|----------|-----------|--------|----------|
| Logistic Regression       | 70.17    | 75.81     | 59.23  | 66.50    |
| Multinomial Naive Bayes      | 65.49    | 82.66     | 39.20  | 53.18    |
| Gaussian Naive Bayes   | 66.97    | 78.28     | 46.98  | 58.72    |

## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش چهارم: ترکیب همه ویژگی‌ها</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
تمام ۹ ویژگی (۳ ساختاری + ۳ آماری + ۳ خلاقانه) را با هم ترکیب کنید.
سپس هر دو مدل را دوباره آموزش دهید و نتایج را ارزیابی کنید.
<br>
آیا ترکیب همه ویژگی‌ها باعث بهبود عملکرد مدل می‌شود؟
<br>
اگر خیر، به نظر شما دلیل آن چیست؟ (مثلاً تداخل بین ویژگی‌ها یا همبستگی بالا و...)
</p>


<p style="direction: rtl; text-align: right; background:#fffbe6; font-family: Vazir; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111">
✍️ <b>پاسخ تشریحی بخش چهارم:</b><br>
ترکیب ویژگی‌ها تا حدی منجر به بهبود عملکرد هر دو نوع مدل در تسک تعریف‌شده شده است، تا جایی که همان‌طور که در جدول ارائه‌شده در آخر این بخش سوال دیده می‌شود، عملکرد مدل رگرسیون در هر چهار معیار بهبود جزئی داشته است؛ همچنین در خصوص مدل بیزی، عملکرد مدل در سه معیار از این چهار معیار بهبود یافته است و عملکرد برتر میان انواع آزمایش‌ها بوده است.
<br>
 این بهبود عملکرد در اثر ترکیب ویژگی‌ها می‌تواند بیانگر این باشد که ادغام ویژگی‌ها باعث شده است تا دانش مدل نسبت به دادۀ مورد استفاده افزایش یابد و در حقیقت، هر نوع ویژگی، یک جنبه و بُعد (مانند ساختار، محتوا و...) از اطلاعات را به دانش مدل اضافه کرده‌اند و به نوعی در نقش مکمل یکدیگر در ابعاد مختلف دانش از داده ظاهر شده‌اند. همچنین می‌توان نتیجه گرفت وجود همبستگی میان ویژگی‌ها از دسته‌های متفاوت به قدری نبوده است که عملکرد مدل را تحت تاثیر قرار دهد و سطح معقول و مناسبی از همبستگی میان انواع ویژگی‌ها برقرار بوده است.
</p>


In [ ]:
def concat_features(features_dfs):
    final_df = pd.DataFrame([])
    for df in features_dfs:
        df = df.drop(['status'], axis=1)
        final_df = pd.concat([final_df, df], axis=1)
    return pd.concat([final_df, features_dfs[0]['status']], axis=1)

final_df = concat_features([features_df, cont_features_df, creative_features_df])
print(final_df.shape)
print(final_df.head())

(11430, 10)
   nb_dots  nb_slashes  nb_hyphens  length_url  ratio_digit_url  \
0        3           3           0          37         0.000000   
1        1           5           0          77         0.220779   
2        4           5           1         126         0.150794   
3        2           2           0          18         0.000000   
4        2           5           2          55         0.000000   

   longest_words_raw  suspicious_char_ratio  tld_risk  brand_count      status  
0                 11               0.189189         0            0  legitimate  
1                 19               0.090909         0            0    phishing  
2                 13               0.150794         0            5    phishing  
3                  5               0.277778         0            0  legitimate  
4                 11               0.181818         0            0  legitimate  


In [169]:
X = final_df.drop(['status'], axis=1)
y = [labels_dict[lbl] for lbl in list(cont_features_df['status'])]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [170]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)
y_pred_lr = log_reg.predict(X_test_scaled)

In [171]:
gnb = GaussianNB()
gnb.fit(X_train_scaled, y_train)
y_pred_nb_gaussian = gnb.predict(X_test_scaled)

In [172]:
metrics_lr = get_metrics(y_test, y_pred_lr)
metrics_nb_gs = get_metrics(y_test, y_pred_nb_gaussian)

print('Logistic Regression Model:', *[(key, f'{val:.4f}') for (key, val) in metrics_lr.items()], sep='\n')
print('\nGaussian Naive Bayes model:', *[(key, f'{val:.4f}') for (key, val) in metrics_nb_gs.items()], sep='\n')

Logistic Regression Model:
('accuracy', '0.7410')
('precision', '0.7688')
('recall', '0.6894')
('f1', '0.7269')

Gaussian Naive Bayes model:
('accuracy', '0.7450')
('precision', '0.8440')
('recall', '0.6010')
('f1', '0.7021')


To visualize the comparison:

| Model                     | Accuracy(%) | Precision(%) | Recall(%) | F1 Score(%) |
|---------------------------|----------|-----------|--------|----------|
| Logistic Regression       | 74.10    | 76.88     | 68.94  | 72.69    |
| Gaussian Naive Bayes      | 74.50    | 84.40     | 60.10  | 70.21    |

Now, to be able to compare the effect of different set of features on the performance of the models, here's the complete metrics' comparison:

**Final Model & Feature Types Performance Summary**

| Experiment Type                    | Model                       | Accuracy(%) | Precision(%) | Recall(%)  | F1(%)     |
|-----------------------------------|------------------------------|----------|-----------|---------|--------|
| **Combined Features**             | Logistic Regression          | 74.10   | 76.88    | 68.94  | **72.69** |
|                                   | Gaussian Naive Bayes         |**74.50**|**84.40** | 60.10  | 70.21 |
| **Creative Features**             | Logistic Regression          | 70.17   | 75.81    | 59.23  | 66.50 |
|                                   | Multinomial Naive Bayes      | 65.49   | 82.66    | 39.20  | 53.18 |
|                                   | Gaussian Naive Bayes         | 66.97   | 78.28    | 46.98  | 58.72 |
| **Statistical & Contextual**      | Logistic Regression          | 64.83   | 69.55    | 52.76  | 60.00 |
|                                   | Gaussian Naive Bayes         | 63.87   | 75.69    | 40.86  | 53.07 |
| **Structural Features**           | Logistic Regression          | 67.63   | 70.42    | 60.80  | 65.26 |
|                                   | Multinomial Naive Bayes      | 54.24   | 52.86    |**78.30**| 63.12 |


## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش پنجم: جمع‌بندی نهایی</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
نتیجه‌گیری نهایی خودتان از این سوال را ارائه دهید. برای مثال باید "حداقل" به سوال‌های زیر پاسخ دهید:
<br>
- کدام مدل برای این نوع داده بهتر عمل کرده است؟ چرا؟
<br>
- کدام نوع ویژگی بیشترین تأثیر را داشته است؟ کدام نوع کمترین؟ چرا؟
<br>
- نرمال‌سازی نیاز بوده است؟ اگر بله، برای هر دو مدل؟ چرا؟
<br>
- غیر از استخراح ویژگی از خود آدرس اینترنتی، چه رویکرد دیگری می‌توان اتخاذ نمود؟
</p>


<p style="direction: rtl; text-align: right; background:#fffbe6; font-family: Vazir; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111">
✍️ <b>پاسخ تشریحی بخش پنجم:</b>
<br><br>
در این مرحله به جمع‌بندی از آزمایشات صورت گرفته در سوال دوم می‌پردازیم. در این سوال، دو نوع مدل رگرسیون و بیزی به همراه انواع ویژگی‌ها با یکدیگر مقایسه شدند و عملکرد هر مدل بر روی هر نوع از ویژگی‌ها توسط چهار معیار ارزیابی شد که نتیجۀ حاصل را می‌توان در جدول آخر قسمت چهارم این سوال مشاهده کرد. با توجه به مقادیر معیارها در هر حالت، یافته‌های زیر قابل ارائه است:
<br><br>
1- به طور میانگین و با توجه به مقادیر معیارها، می‌توان گفت مدل رگرسیون نسبت به مدل‌های بیزی عملکرد بهتری داشته است، هر چند که اختلاف میان آن‌ها بسیار ناچیز می‌باشد و حتی در موارد جزئی در برخی معیارها برتری با مدل بیزی می‌باشد. این برتری مدل رگرسیون می‌تواند دلایل مختلفی داشته باشد، که از مهم‌ترین آن‌ها می‌تواند  به موارد زیر اشاره کرد:
<br>
- مدل رگرسیون فرضی بر استقلال ویژگی‌ها ندارد در حالی که مدل بیزی فرض بر استقلال ویژگی‌ها می‌کند، در حالی که با توجه به 9 ویژگی نهایی واضح است که ویژگی‌ها از یک‌دیگر به طور کامل مستقل نیستند؛ برای مثال سه ویژگی ساختاری و یا ویژگی نسبت ارقام و یا حروف غیرمتعارف با طول آدرس رابطه دارند و این عدم استقلال می‌تواند در عملکرد مدل بیزی تاثیر بگذارد.
<br>
- در مواردی که از مدل بیزی گاوسی استفاده شده است، می‌دانیم که این مدل فرض بر نرمال بودن تویع مقادیر ویژگی می‌کند که این فرض نیست لزوما فرض درستی نیست و همانند فرض استقلال می‌تواند بر عمکلرد مدل تاثیرگذار باشد؛ حال آن که مدل رگرسیون بدون هیچ گونه فرضی و با یادگیری روابط میان ویژگی‌ها عملکرد خود را بهبود می‌بخشد.
<br>- 
همان‌طور که اشاره شد، با توجه به رابطۀ مدل رگرسیون که از ترکیب ویژگی‌ها با یکدیگر، تصمیم نهایی اتخاذ می‌شود، این مدل می‌تواند ترکیب و تاثیر میان ویژگی‌ها را به مراتب بهتر از مدل‌های بیزی مدل کند و بفهمد و همین مورد باعث می‌شود، برخلاف مدل بیزی که تاثیر ویژگی‌ها را بر یکدیگر نادیده می‌گیرد، مدل رگرسیون از این تاثیر استفاده کند و از آن در بهبود عملکرد خود بهره گیرد.
<br>
این موارد در کنار موارد دیگر می‌توانند از دلایل عملکرد هر چند جزئی ولی بهتر و با ثبات‌تر مدل رگرسیون در مقایسه با مدل‌های بیزی باشند.
<br><br>
2- همان‌طور که دیده می‌شود، تاثیر ادغام ویژگی‌ها بریکدیگر باعث شده است تا عملکرد آن‌ها در حالت ادغام از عملکرد هر مجموعه به تنهایی بهتر باشد، با این حال، با توجه به مقدار هر معیار و به خصوص معیار f1 در هر حالت، می‌توان نتیجه گرفت که در میان سه دسته ویژگی استخراج شده، ویژگی‌های خلاقانه و ویژگی‌های ساختاری تاثیر قابل توجه‌تری نسبت به ویژگی‌های محتوایی داشته اند. دلیل برتری ویژگی‌های خلاقانه را می‌توان ارتباط نزدیک‌تر با نمونه‌های فیشینگ و تعدد بیشتر در وقوع در میان نمونه‌های فیشینگ دانست، که باعث کمک بیشتر به مدل برای تشخیص این نوع آدرس‌ها شده است.
<br>
با این حال، برای تشخیص فیشینگ، نیاز به همۀ ابعاد محتوا، ساختار و ویژگی‌های دیگر می‌باشد که این مورد در حالت ادغام ویژگی‌ها و برتری این حالت نسبت به حالاتی که تنها از یک مجموعه ویژگی استفاده شده است، به خوبی قابل مشاهده است و نشان از لزوم استفاده از چند بعد برای انجام این تسک دارد.
<br><br>
3- در مورد نحوۀ تغییر مقادیر داده و انجام نرمال‌سازی، همان‌طور که گفته شد، به علت اینکه مدل رگرسیون به طور مستقیم با مقادیر ویژگی‌ها سر و کار دارد، نرمال‌سازی گامی مهم در پردازش داده محسوب می‌شود و برای این مدل نیاز است؛ اما در مدل‌های بیزی و مخصوصا مدل Multinomial، انجام نرمال‌سازی نیاز نیست، چرا که توزیع و احتمال هر ویژگی نسبت به خود حساب شده و از آن جایی که نرمال‌سازی، نسبت مقادیر موجود در یک ویژگی را تحت تاثیر قرار نمی‌دهد، انجام نرمال‌سازی عملی تاثیرگذار نخواهد بود. در خصوص مدل گاوسی نیز، در صورتی که نرمال‌سازی سبب راحتی بیشتر در محاسبات و مواردی از این قبیل شود، می‌توان آن را انجام داد. همچنین برای اینکه مقایسه با مدل رگرسیون به طور کاملا مساوی صورت گیرد، نرمال‌سازی از این جهت نیز می‌تواند ثمربخش باشد.
<br><br>
4- از رویکردهای متنوعی می‌توان بهره برد که یکی از آن‌ها می‌تواند استفاده از مدل‌های پیچیده‌تری باشد که بتوانند خود ویژگی‌های داده را یاد بگیرند. از مهم‌ترین این مدل‌ها می‌توان به مدل‌های یادگیری عمیق مانند CNN یا RNN مبتنی بر ورودی کاراکتر و یا مدل‌های مبتنی بر معماری Transformer اشاره کرد که با گرفتن دادۀ خام می‌توانند ویژگی‌های مناسب داده را در لایه‌های درونی و پنهان خود استخراج کنند و عملا وظیفۀ استخراج ویژگی را خود انجام می‌دهند و در فرآیند یادگیری دخیل می‌کنند.
</p>


# <h1 style="text-align: right;">**نکات مهم و قوانین تحویل**</h1>



<h4 dir="rtl" style="font-family: Vazir; width: 85%;">فایل ارسالی شما باید با فرمت زیر نامگذاری شود: <code>NLP_CA{n}_{LASTNAME}_{STUDENTID}.ipynb</code></h4>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">نحوه انجام تمرین:</h4>
<ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
  <li>سلول‌های کد با برچسب <code>WRITE YOUR CODE HERE</code> را تکمیل کنید.</li>
  <li>برای پاسخ‌های متنی، متن <code>{{پاسخ_خود_را_اینجا_بنویسید}}</code> را با پاسخ خود جایگزین کنید.</li>
</ul>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">صداقت علمی:</h4> <ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;"> <li>ما نوت‌بوک‌های تعداد مشخصی از دانشجویان که به صورت تصادفی انتخاب می‌شوند، بررسی خواهیم کرد. این بررسی‌ها اطمینان حاصل می‌کنند که کدی که نوشتید واقعاً پاسخ‌های موجود در نوت‌بوک شما را تولید می‌کند. اگر پاسخ‌های صحیح را در نوت‌بوک خود بدون کدی که واقعاً آن پاسخ‌ها را تولید کند تحویل دهید، این یک مورد جدی از عدم صداقت علمی محسوب می‌شود.</li> <li>ما همچنین بررسی‌های خودکاری را برای تشخیص سرقت علمی در نوت‌بوک‌های کولب انجام خواهیم داد. کپی کردن کد از دیگران نیز یک مورد جدی از عدم صداقت علمی محسوب می‌شود.</li> </ul>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">توضیحات تکمیلی:</h4> <ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
<li>
خوانایی و دقت بررسی‌ها در گزارش نهایی از اهمیت ویژه‌ای برخوردار است. به تمرین‌هایی که به صورت کاغذی تحویل داده شوند یا به صورت عکس در سایت بارگذاری شوند، ترتیب اثری داده نخواهد شد.</li>
<li>
 همه‌ی کدهای پیوست گزارش بایستی قابلیت اجرای مجدد داشته باشند. در صورتی که برای اجرا مجدد آن‌ها نیاز به تنظیمات خاصی می‌باشد، بایستی تنظیمات مورد نیاز را نیز در گزارش خود ذکر کنید.  دقت کنید که  تمامی کدها باید توسط شما اجرا شده باشند و نتایج اجرا در فایل کدهای ارسالی مشخص باشد. به کدهایی که نتایج اجرای آن‌ها در فایل ارسالی مشخص نباشد نمره‌ای تعلق نمی‌گیرد.
</li>
<li>توجه کنید این تمرین باید به صورت تک‌نفره انجام شود و پاسخ‌های ارائه شده باید نتیجه فعالیت فرد نویسنده باشد (همفکری و به اتفاق هم نوشتن تمرین نیز ممنوع است). در صورت مشاهده
 تشابه به همه افراد مشارکت‌کننده، نمره تمرین صفر و به استاد گزارش می‌گردد.
 </li>

 <li>
لطفاً تمامی پاسخ‌های متنی خود را با <b>فونت وزیر (Vazir)</b> و به‌صورت <b>راست‌چین</b> بنویسید.  
از استفاده از فونت‌های پیش‌فرض خودداری کنید تا ظاهر نوت‌بوک شما یک‌دست و خوانا باشد.  
در بخش‌های تشریحی، سعی کنید پاسخ‌ها را کامل، منسجم و با رعایت نگارش فارسی بنویسید.  
همچنین، به چینش تمیز سلول‌ها و اجرای درست کدها توجه کنید تا تمرین شما با فرمت خواسته‌شده و استاندارد ارائه شود.
</li>
 <li>برای مطالعه بیشتر درباره‌ی فرمت Markdown می‌توانید از <a href="https://github.com/tajaddini/Persian-Markdown/blob/master/learn-MD.md">این لینک</a> مطالعه کنید.
 </li>
 </ul>
    

 </div>
